[package]
name = "frunk_proc_macros"
version = "0.0.3"
authors = ["Lloyd <lloydmeta@gmail.com>"]
description = "Proc macros for Frunk"
license = "MIT"
documentation = "https://docs.rs/frunk_proc_macros"
repository = "https://github.com/lloydmeta/frunk"
keywords = ["Frunk", "macros"]

[badges]
travis-ci = { repository = "lloydmeta/frunk" }

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"

[dependencies.frunk_proc_macro_helpers]
path = "../proc-macro-helpers"
default-features = false
version = "0.0.3"

[dependencies.frunk_core]
path = "../core"
default-features = false
version = "0.3.0"

[dev-dependencies.frunk]
path = "../."
default-features = false
version = "0.3.0"